spring:
  application:
    name: booklay-front

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://133.186.218.11:8888/${spring.application.name}/${spring.profiles.active}"