spring:
  application:
    name: booklay-front

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://133.186.218.11:8888"

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    cache: false

server:
  tomcat:
    use-relative-redirects: true