# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: [[https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven&#93;(https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven)](https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven](https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven))

name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name : Run SonarQube
        run : mvn sonar:sonar
          -Dsonar.projectKey=github-action
          -Dsonar.host.url=${{secrets.SONAR_HOST}}
          -Dsonar.login=${{secrets.SONAR_TOKEN}}

      #################
      # Front Server 1 #
      #################

      - name: ready for deploy first server (execute shell script)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: "./unhealth.sh"

#      - name: Sleep for 60 seconds
#        uses: jakejarvis/wait-action@master
#        with:
#          time: '60s'

      - name : upload file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/*.jar"
          target: "~/"
          rm: false

      - name: execute startup script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: "./startup.sh"

#      - name: Sleep for 30 seconds
#        uses: jakejarvis/wait-action@master
#        with:
#          time: '30s'

      #################
      # Front Server 2 #
      #################

#      - name: ready for deploy second server (execute shell script) 2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_IP_2 }}
#          username: ${{ secrets.SSH_ID_2 }}
#          key: ${{ secrets.SSH_KEY_2 }}
#          port: ${{ secrets.SSH_PORT_2 }}
#          script_stop: true
#          script: "./unhealth.sh"
#
#      - name: Sleep for 60 seconds 2
#        uses: jakejarvis/wait-action@master
#        with:
#          time: '60s'

      - name: upload file 2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP_2 }}
          username: ${{ secrets.SSH_ID_2 }}
          key: ${{ secrets.SSH_KEY_2 }}
          port: ${{ secrets.SSH_PORT_2 }}
          source: "target/*.jar"
          target: "~/"
          rm: false

      - name: execute startup script 2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP_2 }}
          username: ${{ secrets.SSH_ID_2 }}
          key: ${{ secrets.SSH_KEY_2 }}
          port: ${{ secrets.SSH_PORT_2 }}
          script_stop: true
          script: "./startup.sh"

#      - name: Sleep for 30 seconds 2
#        uses: jakejarvis/wait-action@master
#        with:
#          time: '30s'